services:

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_LISTEN_PORT: "5050"
    ports:
      - "5050:5050"